name: Platform IO CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pio-env: ['esp12e', 'esp32dev']
        example: ['Blink/Blink.ino', 'Do/Do.ino', 'FromArray/FromArray.ino', 'FromProperty/FromProperty.ino', 'FromSerialPort/FromSerialPort.ino', 'FromString/FromString.ino', 'GlobalDefined/GlobalDefined.ino', 'Reduce/Reduce.ino']
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install PlatformIO
        run: python -m pip install platformio
      - name: Build firmware
        run: pio ci --lib="." --board ${{matrix.pio-env}}  "./examples/${{matrix.example}}"
